import './admin-user';
import './profile-edit-profile';
import './profile-edit-password';
import './category';
import './tab';
import './application';
import './setting';
import './page';
import './upload';
